from __future__ import annotations

import sys
from pathlib import Path

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F
from pyspark.sql import types as T
from pyspark.sql.window import Window


# ============================================================
# CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent

INPUT_PATH = PROJECT_ROOT / "logs" / "queries.jsonl"

PROCESSED_PATH = PROJECT_ROOT / "data" / "processed" / "queries"

QUARANTINE_PATH = PROJECT_ROOT / "data" / "quarantine" / "queries"

APP_NAME = "RAG-Quality-Analytics-PySpark"


# ============================================================
# SPARK SESSION
# ============================================================

def create_spark_session() -> SparkSession:
    """
    Create a local Spark session suitable for development/testing.
    """
    return (
        SparkSession.builder
        .appName(APP_NAME)
        .master("local[*]")
        .config("spark.sql.session.timeZone", "UTC")
        .config("spark.sql.parquet.compression.codec", "snappy")
        .config("spark.sql.sources.partitionOverwriteMode", "dynamic")
        .getOrCreate()
    )


# ============================================================
# VALIDATE INPUT
# ============================================================

def validate_input() -> None:
    """
    Fail early if the expected source file does not exist.
    """
    if not INPUT_PATH.exists():
        raise FileNotFoundError(
            f"\nInput file not found:\n{INPUT_PATH}\n\n"
            "Expected:\n"
            "logs/queries.jsonl"
        )

    if INPUT_PATH.stat().st_size == 0:
        raise ValueError(
            f"\nInput file is empty:\n{INPUT_PATH}"
        )


# ============================================================
# READ JSONL
# ============================================================

def read_source(spark: SparkSession) -> DataFrame:
    """
    Read JSON Lines using Spark's permissive mode.
    Malformed JSON is captured in _corrupt_record instead of crashing.
    """
    print("\n[1/6] Reading source data...")

    df = (
        spark.read
        .option("mode", "PERMISSIVE")
        .option("columnNameOfCorruptRecord", "_corrupt_record")
        .json(str(INPUT_PATH))
    )

    print(f"Input columns: {df.columns}")
    return df


# ============================================================
# HANDLE MALFORMED RECORDS
# ============================================================

def quarantine_malformed(
    df: DataFrame,
    spark: SparkSession
) -> DataFrame:
    """
    Separate malformed JSON records from valid records.
    """
    print("\n[2/6] Checking malformed records...")

    if "_corrupt_record" not in df.columns:
        print("No corrupt-record column generated by Spark.")
        return df

    malformed = (
        df
        .filter(F.col("_corrupt_record").isNotNull())
        .select("_corrupt_record")
    )

    malformed_count = malformed.count()

    if malformed_count > 0:
        print(f"WARNING: {malformed_count} malformed record(s) found.")
        malformed.write.mode("append").text(str(QUARANTINE_PATH))
        print(f"Malformed records → {QUARANTINE_PATH}")
    else:
        print("No malformed records found.")

    valid = df.filter(F.col("_corrupt_record").isNull())
    return valid.drop("_corrupt_record")


# ============================================================
# CLEANING & DEDUPLICATION
# ============================================================

def clean_data(df: DataFrame) -> DataFrame:
    """
    Clean and standardize raw RAG query events.

    Handles:
    - query ID normalization
    - query text normalization
    - timestamp parsing
    - latency metrics
    - token metrics
    - cost
    - nested config extraction
    - data-quality flags
    - duplicate query IDs
    - partition date
    """
    print("\n[3/6] Cleaning and deduplicating data...")
    
    before_count = df.count()

    # ---------------------------------------------------------
    # Query ID
    # ---------------------------------------------------------
    query_id_col = next(
        (col_name for col_name in ["query_id", "queryId", "id"] if col_name in df.columns),
        None
    )

    if query_id_col:
        df = df.withColumn("query_id", F.col(query_id_col).cast("string"))
    else:
        df = df.withColumn("query_id", F.lit(None).cast("string"))

    # ---------------------------------------------------------
    # Query text
    # ---------------------------------------------------------
    query_text_col = next(
        (col_name for col_name in ["query", "question", "query_text", "prompt"] if col_name in df.columns),
        None
    )

    if query_text_col:
        df = df.withColumn("query_text", F.trim(F.col(query_text_col).cast("string")))
    else:
        df = df.withColumn("query_text", F.lit(None).cast("string"))

    # ---------------------------------------------------------
    # Timestamp
    # ---------------------------------------------------------
    timestamp_col = next(
        (col_name for col_name in ["timestamp", "created_at", "createdAt", "event_time", "event_timestamp", "ts"] if col_name in df.columns),
        None
    )

    if timestamp_col:
        df = df.withColumn("event_timestamp", F.to_timestamp(F.col(timestamp_col)))
    else:
        df = df.withColumn("event_timestamp", F.lit(None).cast("timestamp"))

    # ---------------------------------------------------------
    # Helper functions
    # ---------------------------------------------------------
    def numeric_column(name):
        if name in df.columns:
            return F.col(name).cast("double")
        return F.lit(None).cast("double")

    def integer_column(name):
        if name in df.columns:
            return F.col(name).cast("long")
        return F.lit(None).cast("long")

    # ---------------------------------------------------------
    # Latency
    # ---------------------------------------------------------
    df = df.withColumn("retrieval_latency_ms", numeric_column("retrieval_latency_ms"))
    df = df.withColumn("generation_latency_ms", numeric_column("generation_latency_ms"))
    df = df.withColumn("total_latency_ms", numeric_column("total_latency_ms"))

    # Keep latency_ms for compatibility with existing dbt models.
    df = df.withColumn("latency_ms", F.col("total_latency_ms"))

    # ---------------------------------------------------------
    # Tokens
    # ---------------------------------------------------------
    df = df.withColumn("tokens_in", integer_column("tokens_in"))
    df = df.withColumn("tokens_out", integer_column("tokens_out"))
    df = df.withColumn("total_tokens", integer_column("total_tokens"))

    # ---------------------------------------------------------
    # Cost
    # ---------------------------------------------------------
    df = df.withColumn("cost_usd", numeric_column("cost_usd"))

    # ---------------------------------------------------------
    # Nested config
    # ---------------------------------------------------------
    if "config" in df.columns:
        config_schema = T.StructType([
            T.StructField("model", T.StringType(), True),
            T.StructField("chunk_size", T.StringType(), True),
            T.StructField("top_k", T.IntegerType(), True),
            T.StructField("embedding_model", T.StringType(), True),
        ])

        df = df.withColumn("_config", F.from_json(F.to_json(F.col("config")), config_schema))

        df = df.withColumn(
            "model",
            F.when(F.trim(F.col("_config.model")) != "", F.trim(F.col("_config.model"))).otherwise(None)
        )
        df = df.withColumn("top_k", F.col("_config.top_k").cast("int"))
        
        # Preserve complete configuration as JSON.
        df = df.withColumn("config_json", F.to_json(F.col("config")))
        df = df.drop("_config")
    else:
        df = df.withColumn("model", F.lit(None).cast("string"))
        df = df.withColumn("top_k", F.lit(None).cast("int"))
        df = df.withColumn("config_json", F.lit(None).cast("string"))

    # ---------------------------------------------------------
    # Data-quality flags
    # ---------------------------------------------------------
    df = df.withColumn(
        "invalid_query_id",
        F.col("query_id").isNull() | (F.trim(F.col("query_id")) == "")
    )

    df = df.withColumn(
        "invalid_timestamp",
        F.col("event_timestamp").isNull()
    )

    # ---------------------------------------------------------
    # Partition date
    # ---------------------------------------------------------
    df = df.withColumn("dt", F.to_date(F.col("event_timestamp")))

    # ---------------------------------------------------------
    # Deduplicate
    # ---------------------------------------------------------
    valid_ids = df.filter(~F.col("invalid_query_id"))
    invalid_ids = df.filter(F.col("invalid_query_id"))

    window_spec = (
        Window
        .partitionBy("query_id")
        .orderBy(F.col("event_timestamp").desc_nulls_last())
    )

    valid_ids = (
        valid_ids
        .withColumn("_row_number", F.row_number().over(window_spec))
        .filter(F.col("_row_number") == 1)
        .drop("_row_number")
    )

    df = valid_ids.unionByName(invalid_ids, allowMissingColumns=True)
    
    after_count = df.count()
    print(f"Rows before deduplication: {before_count}")
    print(f"Rows after deduplication:  {after_count}")
    print(f"Duplicates removed:        {before_count - after_count}")

    return df


# ============================================================
# FINAL VALIDATION
# ============================================================

def validate_clean_data(df: DataFrame) -> None:
    """
    Validate the cleaned dataset before writing Parquet.
    Invalid IDs are allowed but valid IDs must be strictly unique.
    """
    print("\n[4/6] Validating cleaned data...")

    duplicate_valid_ids = (
        df.filter(~F.col("invalid_query_id"))
        .groupBy("query_id")
        .count()
        .filter(F.col("count") > 1)
        .count()
    )

    if duplicate_valid_ids > 0:
        raise ValueError(f"Validation failed: {duplicate_valid_ids} valid duplicate query_id groups remain.")

    invalid_count = df.filter(F.col("invalid_query_id")).count()
    
    print("✓ Valid query_ids are strictly unique.")
    if invalid_count > 0:
        print(f"ℹ Note: {invalid_count} records flagged with invalid_query_id will be written for quarantine tracking.")


# ============================================================
# WRITE PARQUET
# ============================================================

def write_parquet(df: DataFrame) -> None:
    """
    Write cleaned records to partitioned Parquet storage.
    """
    print("\n[5/6] Writing Parquet...")

    output_columns = [
        "query_id", "query_text", "event_timestamp",
        "latency_ms", "retrieval_latency_ms", "generation_latency_ms", "total_latency_ms",
        "tokens_in", "tokens_out", "total_tokens",
        "cost_usd",
        "model", "top_k", "config_json",
        "invalid_timestamp", "invalid_query_id",
        "dt"
    ]

    (
        df.select(*output_columns)
          .write
          .mode("overwrite")
          .partitionBy("dt")
          .parquet(str(PROCESSED_PATH))
    )

    print(f"Parquet successfully written to:\n{PROCESSED_PATH}")


# ============================================================
# READ-BACK CHECK
# ============================================================

def verify_parquet(spark: SparkSession) -> None:
    """
    Read the produced Parquet back from disk to verify schema and count.
    """
    print("\n[6/6] Verifying Parquet output...")

    parquet_df = spark.read.parquet(str(PROCESSED_PATH))
    count = parquet_df.count()

    print(f"Parquet rows: {count}")
    print("\nParquet schema:")
    parquet_df.printSchema()

    if count == 0:
        raise ValueError("Parquet verification failed: output contains zero rows.")

    print("\n✓ PARQUET CHECKPOINT PASSED")


# ============================================================
# MAIN
# ============================================================

def main() -> None:
    print("=" * 70)
    print("RAG QUALITY ANALYTICS - PYSPARK PIPELINE")
    print("=" * 70)

    validate_input()
    spark = create_spark_session()

    try:
        df = read_source(spark)
        df = quarantine_malformed(df, spark)
        df = clean_data(df)
        validate_clean_data(df)
        write_parquet(df)
        verify_parquet(spark)

        print("\n" + "=" * 70)
        print("PIPELINE COMPLETED SUCCESSFULLY")
        print("=" * 70)

    except Exception as exc:
        print("\n" + "=" * 70)
        print("PIPELINE FAILED")
        print("=" * 70)
        print(f"\nError: {exc}")
        raise

    finally:
        spark.stop()


if __name__ == "__main__":
    main()